### PR TITLE
feat(polymer): migrate to Polymer 2

### PR DESCRIPTION
**Pull request by masonlouchart**
Before this commit the element was only usable inside projects using
Polymer 1. Now, the element is turned hybrid so it also can be used
inside Polymer 2 projects.

### CODE REVIEW

**Comment by masonlouchart** [comment]
Unit tests are not passing I agree, but it drives me crazy because they were never not really executed (see #35) and I need this web component in a Polymer 2 app asap.

**Comment by saeidzebardast** [comment]
@masonlouchart Thank you for efforts. But I we should not break the master branch. I can't merge it into the master branch unless all tests pass.

**Comment by saeidzebardast** [comment]
@masonlouchart I fixed running unit tests. Please do reverse merge from the master branch (or 
 do rebase) to make sure all tests passed.

**Comment by masonlouchart** [comment]
Damn, I worked on unit tests the all night. 😕 

I took a look at your fix and I think we can just execute the content of the callback defined in all listeners instead of fire the event manually.

Please see below my proposal and comment on it:

### Change setup
```javascript
setup(function(done) {
	myEl = fixture('moment-js-fixture');
    if (myEl.isMomentReady) {
    	done();
    } else {
    	myEl.addEventListener('moment-is-ready', function () {
        	// Wait the element is ready before perform unit test.
        	done();
    	});
    }
});
```

### Remove listener from unit test
```javascript
test('ISO Date is valid', function() {
	myEl.set('date', '2011-10-10T10:20:30');
    assert.equal('2011-10-10T10:20:30', myEl.date);
    assert.isTrue(myEl.isValid);
});

test('ISO Date is not valid', function() {
	myEl.set('date', '2011-10-10T10:20:90');
    assert.isFalse(myEl.isValid);
});

// ...
```

The difference is in your solution because of the event, the element recomputes its date. Not in mine. That introduces "interesting" issues like changing the format does not automatically recompute the formatted date.

I think observers are not working because to fix my new issues I had to call them manually inside the good functions (dateChanged, formatChanged, etc...). But it's another topic.

**Comment by masonlouchart** [comment]
I rebased my branch but still have an issue with unit test on shared locale setting. I'll push soon.

**Comment by masonlouchart** [comment]
Polymer 2 and Firefox 57 seem not be friends... 😕 .
Anyone see what I missed?

**Comment by masonlouchart** [comment]
Web Components not properly loaded for the element using Polymer v2 on Firefox.

capture d ecran 2017-12-24 a 13 09 51

NB: when you run unit test suite with `polymer test -l firefox -p` it can happens that there is no logs in the console. Just refresh Firefox page to see them...

**Comment by masonlouchart** [comment]
I guess it's related to https://github.com/webcomponents/webcomponentsjs/issues/699

**Comment by masonlouchart** [comment]
🆘 Help wanted to make the element work with Polymer 2 on Firefox 57+.

**Comment by saeidzebardast** [comment]
@masonlouchart We could ship a new major version of this element which only supports Polymer 2 instead of hybrid support. Is it helpful?

**Comment by masonlouchart** [comment]
It could help. I think using the `web-components-loader` will solve the issue with Firefox 57.

Do you prefer a new PR or just a commit (on this branch) that turns the element into class?

**Comment by saeidzebardast** [comment]
@masonlouchart Please keep working on this branch. I will release it as a new major version which only supports Polymer 2.x. Please also remove unnecessary codes of Polymer 1.x.
Thanks a lot.

**Comment by masonlouchart** [comment]
Hi @saeidzebardast ,

I didn't have yet migrated the element but I tested Polymer 2 with `webcomponentsjs-loader` on Firefox 57 and it didn't work. 😕 

I don't like the idea of lose hour(s) to migrate the element and get the same result...

I'll push a commit to improve locales file loading and language setting sharing. Expect Travis complain about the UT because, you know... FFF... _(the first F is for "Fucking")_.

**Comment by masonlouchart** [comment]
Hi @saeidzebardast,

It's been a while!
Now the element is using class-style syntax and is not hybrid anymore.
Unit tests have been fixed.

See this [Travis CI build](https://travis-ci.org/masonlouchart/moment-js/builds/508184900).

**Comment by saeidzebardast** [comment]
Hi @masonlouchart,

Thanks for the migration. I am going to merge this and release a new major version.

**Pull request merged**
